const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001";

export type PCBuild = { id: string; slug: string; name: string; description: string | null; price: string; status?: "AVAILABLE" | "HIDDEN" | "SOLD"; purpose: string; resolution: string | null; warrantyMonths: number | null; buildTimeDays: number | null; avitoUrl: string | null; images: { id: string; url: string; sortOrder: number }[]; category: { id: string; name: string; slug: string } | null };
export type PCBuildDetail = PCBuild & { components: { id: string; quantity: number; component: { id: string; manufacturer: string; model: string; category: { name: string } | null } }[] };
export async function getPcBuilds(): Promise<PCBuild[]> { try { const res = await fetch(`${API_URL}/pc-builds`, { cache: "no-store" }); if (!res.ok) return []; return res.json(); } catch { return []; } }
export async function getPcBuildBySlug(slug: string): Promise<PCBuildDetail | null> { try { const res = await fetch(`${API_URL}/pc-builds/${slug}`, { cache: "no-store" }); if (!res.ok) return null; return res.json(); } catch { return null; } }
export type RecommendParams = { purpose?: string; budget?: string; resolution?: string; priority?: string };
export async function getRecommendation(params: RecommendParams): Promise<PCBuild | null> { try { const query = new URLSearchParams(Object.entries(params).filter(([, v]) => Boolean(v)) as [string, string][]); const res = await fetch(`${API_URL}/configurator/recommend?${query.toString()}`, { cache: "no-store" }); if (!res.ok) return null; return res.json(); } catch { return null; } }
export function formatPrice(price: string | null): string { return price == null ? "Цена не указана" : new Intl.NumberFormat("ru-RU").format(Number(price)) + " ₽"; }
export function purposeLabel(purpose: string): string { const labels: Record<string, string> = { GAMES: "Игры", WORK: "Работа", MONTAGE: "Монтаж", THREE_D: "3D", STREAMING: "Стриминг", AI: "AI", UNIVERSAL: "Универсальный" }; return labels[purpose] ?? purpose; }
export function resolutionLabel(resolution: string | null): string | null { const labels: Record<string, string> = { R1080P: "1080p", R1440P: "1440p", R4K: "4K" }; return resolution ? labels[resolution] ?? resolution : null; }
export function priorityLabel(priority: string): string { const labels: Record<string, string> = { MAX_FPS: "Максимум FPS", PRICE_PERFORMANCE: "Цена/производительность", SILENCE: "Тишина", APPEARANCE: "Внешний вид", UPGRADABILITY: "Возможность апгрейда" }; return labels[priority] ?? priority; }
export type AdminUser = { sub: string; email: string; role: "ADMIN" | "MANAGER" };
export async function login(email: string, password: string): Promise<{ ok: true } | { ok: false; message: string }> { try { const res = await fetch(`${API_URL}/auth/login`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!res.ok) { const data = await res.json().catch(() => null); return { ok: false, message: data?.message ?? "Не удалось войти" }; } return { ok: true }; } catch { return { ok: false, message: "Backend недоступен" }; } }
export async function logout(): Promise<void> { await fetch(`${API_URL}/auth/logout`, { method: "POST", credentials: "include" }).catch(() => {}); }
export async function getMe(): Promise<AdminUser | null> { try { const res = await fetch(`${API_URL}/auth/me`, { credentials: "include", cache: "no-store" }); if (!res.ok) return null; const data = await res.json(); return data.user ?? null; } catch { return null; } }
export type Lead = { id: string; name: string; contact: string; budget: string | null; purpose: string | null; category: string | null; pcBuildId: string | null; pcBuild: { id: string; name: string; slug: string; price: string } | null; status: string; comment: string | null; createdAt: string };
export async function getLeads(): Promise<Lead[]> { try { const res = await fetch(`${API_URL}/leads`, { credentials: "include", cache: "no-store" }); if (!res.ok) return []; return res.json(); } catch { return []; } }
export type ComponentCategory = { id: string; code: string; name: string };
export type Component = { id: string; categoryId: string; manufacturer: string; model: string; price: string | null; specs: unknown; imageUrl: string | null; inStock: boolean; compatibility: unknown; category: ComponentCategory };
export type ComponentInput = { categoryId: string; manufacturer: string; model: string; price: string; specs?: unknown; imageUrl?: string | null; inStock?: boolean; compatibility?: unknown };
export async function getComponentCategories(): Promise<ComponentCategory[]> { const res = await fetch(`${API_URL}/components/categories`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error("Не удалось загрузить категории"); return res.json(); }
export type ComponentListResponse = { items: Component[]; total: number; offset: number; limit: number; hasMore: boolean; nextOffset: number | null };
export async function getComponents(params: { categoryId?: string; search?: string; stock?: "all" | "in" | "out"; minPrice?: string; maxPrice?: string; sort?: "name-asc" | "name-desc" | "price-asc" | "price-desc" | "stock"; offset?: number; limit?: number } = {}): Promise<ComponentListResponse> {
  const query = new URLSearchParams();
  Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== "") query.set(key, String(value)); });
  const res = await fetch(`${API_URL}/components?${query.toString()}`, { credentials: "include", cache: "no-store" });
  if (!res.ok) throw new Error("Не удалось загрузить комплектующие");
  return res.json();
}
export async function getComponent(id: string): Promise<Component> { const res = await fetch(`${API_URL}/components/${id}`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error("Не удалось загрузить комплектующее"); return res.json(); }
export async function createComponent(input: ComponentInput): Promise<Component> { const res = await fetch(`${API_URL}/components`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось создать комплектующее")); return res.json(); }
export async function updateComponent(id: string, input: Partial<ComponentInput>): Promise<Component> { const res = await fetch(`${API_URL}/components/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось сохранить комплектующее")); return res.json(); }
export async function deleteComponent(id: string): Promise<void> { const res = await fetch(`${API_URL}/components/${id}`, { method: "DELETE", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось удалить комплектующее")); }
export type AdminBuildComponent = { id: string; quantity: number; component: Component };
export type AdminBuild = PCBuild & { components: AdminBuildComponent[] };
export type CompatibilityIssue = { type: "PAIR" | "POWER" | "RULE"; message: string; componentIds?: string[] };
export type CompatibilityResult = { compatible: boolean; buildId: string; issues: CompatibilityIssue[] };
export async function getAdminBuilds(): Promise<AdminBuild[]> { const res = await fetch(`${API_URL}/pc-build-components/builds`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить сборки")); return res.json(); }
export async function getBuildCompatibility(buildId: string): Promise<CompatibilityResult> { const res = await fetch(`${API_URL}/pc-build-components/builds/${buildId}/compatibility`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось проверить совместимость")); return res.json(); }
export async function setBuildComponent(buildId: string, componentId: string, quantity: number): Promise<AdminBuildComponent> { const res = await fetch(`${API_URL}/pc-build-components/builds/${buildId}/components`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ componentId, quantity }) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось сохранить состав сборки")); return res.json(); }
export async function removeBuildComponent(buildId: string, componentId: string): Promise<void> { const res = await fetch(`${API_URL}/pc-build-components/builds/${buildId}/components/${componentId}`, { method: "DELETE", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось удалить комплектующее из сборки")); }
export type PcBuildInput = { slug: string; name: string; description?: string; price: string; status?: "AVAILABLE" | "HIDDEN" | "SOLD"; purpose: string; resolution?: string; warrantyMonths?: number; buildTimeDays?: number; avitoUrl?: string; categoryId?: string };
export type PcBuildCategory = { id: string; name: string; slug: string };
export type AdminPcBuild = PCBuild & { components: AdminBuildComponent[] };
export async function getPcBuildCategories(): Promise<PcBuildCategory[]> { const res = await fetch(`${API_URL}/admin/pc-builds/categories`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить категории сборок")); return res.json(); }
export async function getAdminPcBuilds(): Promise<AdminPcBuild[]> { const res = await fetch(`${API_URL}/admin/pc-builds`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить готовые сборки")); return res.json(); }
export async function createPcBuild(input: PcBuildInput): Promise<AdminPcBuild> { const res = await fetch(`${API_URL}/admin/pc-builds`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось создать сборку")); return res.json(); }
export async function updatePcBuild(id: string, input: Partial<PcBuildInput>): Promise<AdminPcBuild> { const res = await fetch(`${API_URL}/admin/pc-builds/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось сохранить сборку")); return res.json(); }
export async function deletePcBuild(id: string): Promise<void> { const res = await fetch(`${API_URL}/admin/pc-builds/${id}`, { method: "DELETE", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось добавить изображение")); return res.json(); }
export async function addPcBuildImage(id: string, url: string, sortOrder = 0) { const res = await fetch(`${API_URL}/admin/pc-builds/${id}/images`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url, sortOrder }) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось добавить изображение")); return res.json(); }
export async function deletePcBuildImage(id: string, imageId: string): Promise<void> { const res = await fetch(`${API_URL}/admin/pc-builds/${id}/images/${imageId}`, { method: "DELETE", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось удалить изображение")); }
export type CompatibilityRule = { id: string; name: string; description: string | null; rule: Record<string, unknown>; isActive: boolean };
export type CompatibilityRuleInput = { name: string; description?: string | null; rule: Record<string, unknown>; isActive?: boolean };
export async function getCompatibilityRules(): Promise<CompatibilityRule[]> { const res = await fetch(`${API_URL}/admin/compatibility-rules`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить правила совместимости")); return res.json(); }
export async function createCompatibilityRule(input: CompatibilityRuleInput): Promise<CompatibilityRule> { const res = await fetch(`${API_URL}/admin/compatibility-rules`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось создать правило совместимости")); return res.json(); }
export async function updateCompatibilityRule(id: string, input: Partial<CompatibilityRuleInput>): Promise<CompatibilityRule> { const res = await fetch(`${API_URL}/admin/compatibility-rules/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось сохранить правило совместимости")); return res.json(); }
export async function deleteCompatibilityRule(id: string): Promise<void> { const res = await fetch(`${API_URL}/admin/compatibility-rules/${id}`, { method: "DELETE", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось удалить правило совместимости")); }
async function getApiError(res: Response, fallback: string): Promise<string> { const data = await res.json().catch(() => null); const message = data?.message; return Array.isArray(message) ? message.join(", ") : message ?? fallback; }
export type LeadStatus = "NEW" | "IN_PROGRESS" | "CONTACTED" | "CALCULATED" | "AGREED" | "ORDER" | "REJECTED";
export type LeadStatusHistory = { id: string; fromStatus: LeadStatus | null; toStatus: LeadStatus; comment: string | null; createdAt: string };
export type AdminLead = { id: string; name: string; contact: string; budget: string | null; purpose: string | null; category: string | null; configuration: Record<string, unknown> | null; pcBuildId: string | null; pcBuild: { id: string; name: string; slug: string; price: string } | null; comment: string | null; status: LeadStatus; createdAt: string; updatedAt: string; statusHistory?: LeadStatusHistory[]; order?: { id: string; number: string } | null };
export async function getLeads(): Promise<AdminLead[]> { const res = await fetch(`${API_URL}/leads`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить заявки")); return res.json(); }
export async function getLead(id: string): Promise<AdminLead> { const res = await fetch(`${API_URL}/leads/${id}`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить заявку")); return res.json(); }
export async function updateLeadStatus(id: string, status: LeadStatus, comment?: string): Promise<AdminLead> { const res = await fetch(`${API_URL}/leads/${id}/status`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, comment }) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось изменить статус заявки")); return res.json(); }

export type AdminOrder = { id: string; number: string; totalPrice: string; costPrice: string | null; profit: string | null; comment: string | null; paymentStatus: string; status: string; createdAt: string; updatedAt: string; customer: { id: string; name: string; phone: string; telegram: string | null }; lead: AdminLead | null; items: { id: string; name: string; price: string; quantity: number; pcBuildId: string | null }[]; payments?: { id: string; amount: string; paidAt: string; method: string | null }[]; statusHistory?: OrderStatusHistory[] } ;
export async function createOrderFromLead(leadId: string): Promise<AdminOrder> { const res = await fetch(`${API_URL}/orders/from-lead/${leadId}`, { method: "POST", credentials: "include" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось создать заказ")); return res.json(); }
export async function getOrders(): Promise<AdminOrder[]> { const res = await fetch(`${API_URL}/orders`, { credentials: "include", cache: "no-store" }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось загрузить заказы")); return res.json(); }

export type OrderStatus = "NEW" | "AWAITING_PAYMENT" | "PAID" | "PURCHASING" | "COMPONENTS_RECEIVED" | "ASSEMBLY" | "TESTING" | "READY" | "ISSUED" | "COMPLETED";
export type PaymentStatus = "UNPAID" | "PARTIALLY_PAID" | "PAID";
export type OrderStatusHistory = { id: string; fromStatus: OrderStatus | null; toStatus: OrderStatus; comment: string | null; createdAt: string };
export async function updateOrder(id: string, data: { status?: OrderStatus; paymentStatus?: PaymentStatus; comment?: string }): Promise<AdminOrder> { const res = await fetch(`${API_URL}/orders/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось изменить заказ")); return res.json(); }
export async function addOrderPayment(id: string, amount: number, method?: string): Promise<AdminOrder> { const res = await fetch(`${API_URL}/orders/${id}/payments`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ amount, method }) }); if (!res.ok) throw new Error(await getApiError(res, "Не удалось добавить оплату")); return res.json(); }
